language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project gitstatistics --token $FIREBASE_TOKEN
